// Enemy champions carrying real gear (docs/CAMPAIGN_PLAN.md DECISION 9, 9-12
// through 9-14).
//
// ── What this is, and what it must never become ─────────────────────────────
//
// A bearer is a full enemy character: a real body of a real type, wearing real
// catalog items, fighting with their mods and abilities, and dropping them when
// you take the field. "A relic you win is one that hurt you."
//
// It stays inside standing principle 1 — the enemy is an abstract challenge,
// not an opponent — because the champion DECIDES nothing. He is data: a harder
// unit with better kit, generated by arithmetic off the encounter's strength
// band. Do not give him a name that persists, a grudge, or a reaction. 9-13
// rejected persistent enemy captains for exactly that reason: a named enemy who
// returns is the beginning of an opponent.
//
// ── Sealed, not rolled at launch ────────────────────────────────────────────
//
// Generation happens where the encounter is DEALT (the raid board at newDay,
// the host at creation) and the result is stored. A card advertises what it
// carries (9-14), so rolling at launch would let a reload reroll the reward the
// player picked the raid FOR — the same reason the augury slots and the mission
// offer are sealed.

import { ITEM_CATALOG, RAID_STRENGTH_BANDS, ENEMY_ARMY } from '../utils/campaignConfig.js'
import { getRandom } from '../utils/dice.js'
import { holdsItem } from './items.js'

// Bands are ordered strongest-first in config; the INDEX from the weak end is
// what scales, so "a handful" is rung 0 and "a strong detachment" is the top.
// Derived from the config array rather than restated, so retuning the bands
// moves this with them.
const BAND_ORDER = [...RAID_STRENGTH_BANDS].map((b) => b.label).reverse()
export const bandRung = (label) => Math.max(0, BAND_ORDER.indexOf(label))
export const TOP_RUNG = BAND_ORDER.length - 1

// How likely a champion rides with a target at all, per rung. A handful of
// foragers rarely has one; a strong detachment usually does. Percentages, and
// BALANCE-DEFERRED like everything else 9a authors.
const BEARER_CHANCE = [15, 35, 60, 85]

// How many pieces he carries, per rung. One at the bottom, a full kit at the
// top — which is what makes a hard card the place to look for a relic.
const BEARER_PIECES = [1, 1, 2, 3]

// The unique relic is only reachable at the TOP rung. Uniques are guaranteed
// recoveries (9-10), so putting one on a trivial card would make the whole
// ladder pointless.
const RELIC_RUNG = TOP_RUNG

// The types an enemy champion may be. Drawn from the host's own composition, so
// a bearer is always something the enemy actually fields — the campaign layer
// checks itself against the engine catalog rather than inventing a creature.
export const bearerTypes = () => Object.keys(ENEMY_ARMY)

// The gear a bearer may carry: character-targeted, and LOOTABLE. A banner is
// neither, and that is not an accident (9-12) — banners sit outside the loot
// path in both directions, so an enemy never carries one to be stripped of.
const gearPool = (unique) =>
  ITEM_CATALOG.filter(
    (row) => row.target === 'character' && (row.lootable ?? true) && Boolean(row.unique) === unique,
  )

// Roll one champion for an encounter of this strength, or null.
//
// `campaign` is read ONLY to keep a unique off the board while the player
// already holds one — winning a second copy of a unique relic is the one thing
// 9-6 says cannot happen, and the draw-time filter is the half that stops the
// card advertising it at all (grantItem defends the other half).
//
// `rand` is injectable so tests can pin exactly who rides out.
export function rollBearer(campaign, strengthBand, rand = getRandom) {
  const rung = bandRung(strengthBand)
  if (rand(1, 100) > BEARER_CHANCE[rung]) return null

  const types = bearerTypes()
  if (types.length === 0) return null
  const type = types[rand(0, types.length - 1)]

  const items = []
  // The relic first, so a top-rung champion who wins the roll gets it rather
  // than filling his slots with helms and having no room left.
  if (rung >= RELIC_RUNG) {
    const relics = gearPool(true).filter((row) => !holdsItem(campaign, row.id))
    if (relics.length > 0 && rand(1, 100) <= 25) items.push(relics[rand(0, relics.length - 1)].id)
  }

  const mundane = gearPool(false)
  // Ordinary kit stacks (9-6), so drawing the same helm twice is legal — but a
  // champion wearing two of one thing reads as a bug rather than as loot, and
  // the slot rules would refuse it on a player anyway.
  const remaining = [...mundane]
  while (items.length < BEARER_PIECES[rung] && remaining.length > 0) {
    const [row] = remaining.splice(rand(0, remaining.length - 1), 1)
    items.push(row.id)
  }

  return { type, items }
}

// The tags a bearer rides under, on the ENEMY side of a placement.
//
// squad_id is not decoration: granted abilities are scoped to squad membership
// in the engine (6-6), so a champion placed as a loner would silently lose
// whatever his relic grants. A tagged squad is honoured down to one member,
// which is what makes his gift actually reach the field.
//
// character_id is what lets the campaign ask whether he FELL. The engine reports
// surviving character ids per side, so one fixed tag answers both "do you loot
// him" (9-11: only the dead are stripped) and "was he one of the target force's
// survivors" (he is an extra body, and counting him would understate the host's
// real losses). Nothing about the id persists — 9-13's rule that the enemy has
// no roster is untouched by reusing one integer per encounter.
export const BEARER_SQUAD_ID = 1
export const BEARER_CHARACTER_ID = 1

// The placement entry for a bearer, built the same way a player character's is:
// from the RECORD, never from a request, with the campaign layer translating
// items into the engine's stat and ability vocabulary.
//
// `squad_id` is not decoration. Granted abilities are scoped to squad
// membership in the engine (6-6), so a champion placed as a loner would silently
// lose whatever his relic grants — a tagged squad is honoured down to one
// member, which is what makes his gift actually reach the field.
export function bearerEntry(bearer, { q, r }, squadId, findItem) {
  const mods = {}
  const granted = new Set()
  const denied = new Set()
  for (const id of bearer?.items ?? []) {
    const row = findItem(id)
    if (!row) continue
    for (const [stat, delta] of Object.entries(row.mods ?? {}))
      mods[stat] = (mods[stat] ?? 0) + delta
    for (const name of row.abilities ?? []) granted.add(name)
    for (const name of row.denies ?? []) denied.add(name)
  }
  return {
    unit_type: bearer.type,
    q,
    r,
    squad_id: squadId,
    squad_name: 'Champion',
    ...(Object.keys(mods).length > 0 ? { squad_mods: mods } : {}),
    ...(granted.size > 0 ? { squad_abilities: [...granted] } : {}),
    ...(denied.size > 0 ? { denied_abilities: [...denied] } : {}),
  }
}
